
name: awesome_drawing_quiz
description: Sample app for &#x27;Adding AdMob Ads to a Flutterr app&#x27; Codelab.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^0.3.9

  # TODO: Add firebase_admob as a dependency

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
